spring:
  profiles:
    active: dev #local #dev

management:
  endpoints:
    web:
      exposure:
        include: "refresh, health, info, env, restart"
  context-path: /

feign:
  hystrix:
    enabled: false

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:15001/eureka}
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/omnia_local?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: update
logging:
  level:
    root: 'WARN'
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'WARN'
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/omnia_dev?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create-drop

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
---
spring:
  profiles: eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
